# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Foursquared' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  target 'FoursquaredTests' do
    inherit! :search_paths
    # Pods for testing
    pod "Cuckoo"
  end

end
